Shazwazza/Examine

- Projects/Examine/LuceneEngine/Providers/LuceneIndexer.cs
I found another issue where Examine do index of Double or Float values, and CurrentCulture uses "," as decimal separator.
I do hard debug to find the wrong code row, but i does not found. I have suspect that the issue is in Lucene.NET.
Whatever, I found a little work around to solve the issue. The issue can be solved simply force use of InvariantCulture during the index process.
This work around will work only when "RunAsync = True".
To solve the issue with "RunAsync = False" I suggest to create a parallel Thread, then wait the end of it. I have not practice with multithread, then I have not do this.
Thanks
> Conversion issue with "," decimal separator

- Projects/Examine/LuceneEngine/Providers/LuceneIndexer.cs
Makes the index-fields dictionary to have case-insensitive keys.
This came about when hooking into the `GatheringNodeData` event.
Take the following code... checks if a "tags" field exists, then processes it.
```csharp
var indexer = ExamineManager.Instance.IndexProviderCollection["MyIndexer"];
indexer.GatheringNodeData += (sender, e) =>
{
if (e.Fields.ContainsKey("tags"))
{
e.Fields["searchTags"] = e.Fields["tags"].Replace(',', ' ');
}
}
```
As long as the field is explicitly named "tags" (lowercase), all is good.  However I experienced a scenario where a field was renamed to "Tags" (title-case), and my code didn't run.
Making the dictionary key lookup to be case-insensitive will handle this scenario.
> Just for reference this happened with Umbraco - a developer created a doc-type …
> Case-insensitive Dictionary for Index Fields

- Projects/Examine/LuceneEngine/SearchResults.cs
This fixes a null reference exception we were getting in Umbraco's `PublishedMediaCache.GetUmbracoMediaCacheValues(int id)` when the index has not been built.
> Fixes a null reference exception when querying an empty index

- src/Examine/ExamineManager.cs
Resolves issue #113 by unregistering the Instance object if it has already been registered.
> Temp 113 - ExamineManager not unregistered from HostingEnvironment

- .gitignore
- src/Examine.AzureDirectory/AzureDirectoryFactory.cs
Hi @Shazwazza,
I was trying to use Azure Directory but I notice if I am using that part of code:
```  var factoryType = ExamineTypeFinder.GetTypeByName(configuredDirectoryFactory);
if (factoryType == null)
throw new NullReferenceException("No directory type found for value: " +
configuredDirectoryFactory);
var directoryFactory = (IDirectoryFactory) Activator.CreateInstance(factoryType);
return directoryFactory.CreateDirectory(dirInfo);
```
just for reference my TypeFinder:
```  public static class ExamineTypeFinder
{
public static Type GetTypeByName(string typeName)
{
var type = BuildManager.GetType(typeName, false);
if (type != null) return type;
// TODO: This isn't very elegant, and will have issues since the AppDomain.CurrentDomain
// doesn't actualy load in all assemblies, only the …
```
> Azure Directory - should have explicit interface implementation

- src/Examine/ExamineManager.cs
Hi Shannon,
I would use ExamineManager with SimpleInjector but actually I noticed it has a private constructor. 
I change that to be public, but would ask if you had any reason to make that private?
> Make possible to use SimpleInjector with ExamineManager

- src/Examine.AzureDirectory/AzureDirectory.cs
- src/Examine.AzureDirectory/AzureDirectoryFactory.cs
- src/Examine.AzureDirectory/AzureIndexInput.cs
- src/Examine.AzureDirectory/AzureIndexOutput.cs
- src/Examine.AzureDirectory/Examine.AzureDirectory.csproj
- src/Examine.AzureDirectory/packages.config
The original WindowsAzure.Storage package is now deprecated (https://github.com/Azure/azure-storage-net). This pull request migrates to the supported Microsoft.Azure.Storage package.
> remove deprecated Microsoft.WindowsAzure.Storage.Blob package

- src/Examine/Examine.csproj
- src/Examine/LuceneEngine/LuceneSearchResults.cs
- src/Examine/LuceneEngine/LuceneSearchResultsBase.cs
- src/Examine/SearchResultsBase.cs
One thing I found painful when building [Examine Facets](https://github.com/callumbwhyte/examine-facets) was implementing the `ISearchResults` interface.
The `LuceneSearchResults` class contains a lot of complex logic for paging and building results from a `Document`. However it only has an internal constructor so it can't be easily reused. This is probably fine as in most cases you won't want all the search logic, but the paging is likely going to be needed in almost all implementations.
I created by own [abstract search results class](https://github.com/callumbwhyte/examine-facets/blob/dev/src/Examine.Facets/Search/FacetSearchResultsBase.cs) for facets but again it would cool if a lot of this could be re-used from Examine directly.
This PR standardises some of the helpful paging logic …
> Abstract base class for Search Results

- src/Examine/LuceneEngine/Providers/BaseLuceneSearcher.cs
- src/Examine/LuceneEngine/SearchCriteria/LuceneSearchCriteria.cs
- src/Examine/LuceneEngine/SearchResults.cs
Prevent NotSupportedException being thrown when calling ExtractTerms when a query includes a TermRangeQuery, WildcardQuery or FuzzyQuery as these types of queries throw NotSupportedException for their implementation of ExtractTerms.
> Prevent NotSupportedException being thrown for queries including TermRangeQuery, WildcardQuery and FuzzyQuery

- src/Examine/LuceneEngine/Search/LuceneSearchQueryBase.cs
This fixes https://github.com/Shazwazza/Examine/issues/187 by always escaping the value for `SimpleWildcard` and `ComplexWildcard` Examine values.
> Escape simple/complex wildcard value

- src/Examine/LuceneEngine/Providers/LuceneIndex.cs
What?
Allow for replacing the writerfactory method in LuceneIndex.
Why?
Allows for changing the Merge Policy and DeletionPolicy when using a remote directory.
> Allow implementing WriterFactory in LuceneIndex

- src/Examine/LuceneEngine/Search/LuceneSearchQueryBase.cs
I have no idea how to provoke this with a unit-test, but when using `GroupedOr` on all search fields, with `new ExamineValue(Examineness.Boosted, x, 1.5f)`, my queries blow up with a nullref exception in `GetFieldInternalQuery`.  
It blows up on the built-in field "icon" with the phrase "this".  
I'm sure it's a default stop word and lucene throws it out, but it should be up to Examine to handle that null.  
I've tested this fix manually and it does indeed cure our site. 😇
> Handle queryparser returning null for boosted fields

- src/Examine.Lucene/Search/LuceneSearchOptions.cs
- src/Examine.Lucene/Search/LuceneSearchQuery.cs
@Shazwazza I saw the AllowLeadingWildcards option wasn't being used anymore, and I wasn't sure if that was intentional, or if that was just in the push to get everything up that got lost or didn't get into rev 1.  If it wasn't intentionally removed, I have this pull request that allows you to set it and the other options from the `Lucene.Net.QueryParsers.Flexible.Standard.ICommonQueryParserConfiguration` interface.  Since I wasn't sure if it was intentional, I didn't open an issue on it, but I can open an issue and link it to this if you'd like.
> Set Lucene search options on the parser

- docs/searching.md
Removing the `_` in this example here: https://shazwazza.github.io/Examine/searching
> Remove underscore from searcher

- src/Examine.Core/BaseIndexProvider.cs
I pointed this PR at the release branch, cause the `dev` branch seemed different 🤔 
- Added proper handling of filtered items
I was trying to follow the documentation for custom indexing and trying to exlude/include different fields from my member index, and even though the filter had the correct "includeFields" and "exludeField" i could still find my member with properties that should no longer be in the index
> Handle filtered items

- src/Examine.Lucene/ExamineReplicator.cs
- src/Examine.Lucene/Indexing/IndexFieldValueTypeBase.cs
- src/Examine.Lucene/LoggingInfoStream.cs
- src/Examine.Lucene/Providers/LuceneIndex.cs
Avoid logging allocations when debug logging level is not enabled.
Checks if the debug log level is enabled before calling log debug methods. This saves on creating the params array, saving allocations, improving performance.
> Improve logging performance.

- .github/workflows/build.yml
- src/Examine.Test/Examine.Test.csproj
This updates the packages found in the test project to newer versions.
It includes:
- Framework update to .Net 6.0
- Microsoft.Extensions.Hosting 6.0.1
- Microsoft.Extensions.Logging 6.0.0
- Microsoft.Extensions.Logging.Console 6.0.0
- Microsoft.NET.Test.Sdk 17.3.2
- Moq 4.18.2
- NUnit 3.13.3
- Nunit3TestAdapter 4.2.1
- System.Configuration.ConfigurationManager 6.0.1
- Switch from Microsoft.Azure.Storage.Blob to Azure.Storage.Blob 12.13.1
> chore(deps): Updated dependencies in the test project

- src/Examine.Lucene/Directories/FileSystemDirectoryFactory.cs
- src/Examine.Lucene/Directories/SyncedFileSystemDirectoryFactory.cs
After reading the XML documentation on `FSDirectory` in Lucene.NET it seems that the most optimal way to determine an implementation is using the `FSDirectory.Open` method. (https://github.com/apache/lucenenet/blob/c0c480409e2d3424fbdcc563426c66cacbf72632/src/Lucene.Net/Store/FSDirectory.cs#L35-L87)
[FSDirectory.Open link](https://github.com/apache/lucenenet/blob/c0c480409e2d3424fbdcc563426c66cacbf72632/src/Lucene.Net/Store/FSDirectory.cs#L133-L158)
Is there any specific reason to choose the `SimpleFSDirectory` always?
> fix: Let FSDirectory choose an implementation

- src/Directory.Build.props
- src/Examine.Core/Examine.Core.csproj
- src/Examine.Host/Examine.csproj
- src/Examine.Lucene/Examine.Lucene.csproj
- src/Examine.Lucene/Search/LuceneSearchQuery.cs
- src/Examine.Test/Examine.Lucene/Search/FluentApiTests.cs
fixes: #314 
depends on: #307 for `.Net 6.0` target.
This adds `DateOnly` support to the `RangeQuery` method by checking the type of the generic argument and changing the value to `DateTime` on the fly. Thereby not needing new indexing.
**Note: `DateOnly` is only supported in `Net 6.0` and above**
> Add `DateOnly` support to `RangeQuery` (#314 & #307)

- docs/sorting.md
> Added docs on limiting results

- docs/sorting.md
- src/Examine.Core/EmptySearchResults.cs
- src/Examine.Core/Search/QueryOptions.cs
- src/Examine.Lucene/Search/ILuceneSearchResults.cs
- src/Examine.Lucene/Search/LuceneQueryOptions.cs
- src/Examine.Lucene/Search/LuceneSearchExecutor.cs
- src/Examine.Lucene/Search/LuceneSearchExtensions.cs
- src/Examine.Lucene/Search/LuceneSearchResult.cs
- src/Examine.Lucene/Search/LuceneSearchResults.cs
- src/Examine.Lucene/Search/SearchAfterOptions.cs
- src/Examine.Test/Examine.Lucene/Search/FluentApiTests.cs
Support for efficient deep paging in lucene.net. 
Uses SearchAfter instead of Search when the SearchAfterOptions are available.
This allows lucene to efficiently skip documents before the last document from the previous page fetched for a search.
Steps:
1. Build and execute your query as normal.
2. Cast the ISearchResults from IQueryExecutor.Execute to ILuceneSearchResults
3. Store ILuceneSearchResults.SearchAfter (SearchAfterOptions) for the next page. It may be worth serializing this class and cryptographically hashing it to prevent tampering in a web application so that it can be made available to the next request for the next page.
4. Create the same query as the previous request.
5. When calling IQueryExecutor.Execute. Pass in new LuceneQueryOptions(skip,take, SearchAfterOptions); …
> Support for efficient deep paging in lucene.net

- docs/indexing.md
- docs/v2/articles/indexing.md
- src/Examine.Lucene/Providers/LuceneIndex.cs
Adds to #191 
Also added a XML comment to the `LuceneIndex.IndexCommitted` event
> Added docs on Indexing events

- docs/developerguides/buildtest.md
- docs/developerguides/codestructure.md
- docs/developerguides/docsite.md
- docs/developerguides/roadmap.md
- docs/developerguides/toc.yml
- docs/docfx.json
- docs/toc.yml
Renames the Articles section to User Guide (no links break).
Adds a developer guide section
> Add Developer Guide to docs site

- src/Examine.Core/ValueSet.cs
- src/Examine.Test/Examine.Core/ValueSetTests.cs
This change updates the yield helper method that converts an `IDictionary<string, object>` to an `IDictionary<string, IEnumerable<object>>`.
This allows for greater flexibility when constructing valueSets. Currently, if you have a single field that requires multiple values (say for faceting), you must use the `IDictionary<string, IEnumerable<object>>` overload and wrap all your fields in arrays or other enumerable structures. This change means that you can submit an array for a field and it will be automatically interpreted correctly.
Before - with all other fields wrapped in arrays:
```
var multiValues = new Dictionary<string, IEnumerable<object>>
{
// this is a special field used to display the content name in the Examine dashboard
[UmbracoExamineFieldNames.NodeNameFieldName] = new[] { …
```
> Allow mix of single objects and enumerables in valueset

- src/Examine.Core/FieldDefinition.cs
- src/Examine.Core/IndexOperation.cs
- src/Examine.Core/PublicAPI.Unshipped.txt
- src/Examine.Core/Search/ExamineValue.cs
- src/Examine.Core/Search/SortableField.cs
- src/Examine.Core/ValueSetValidationResult.cs
- src/Examine.Lucene/Directories/FileSystemDirectoryFactory.cs
- src/Examine.Lucene/Directories/SyncedFileSystemDirectoryFactory.cs
- src/Examine.Lucene/ExamineReplicator.cs
- src/Examine.Lucene/Providers/LuceneIndex.cs
- src/Examine.Lucene/PublicAPI.Unshipped.txt
- src/Examine.Lucene/Search/LuceneSearchQueryBase.cs
- src/Examine.Test/Examine.Lucene/Directories/SyncedFileSystemDirectoryFactoryTests.cs
- src/Examine.Test/Examine.Lucene/ExamineReplicatorTests.cs
- src/Examine.Test/Examine.Test.csproj
- src/Examine.Test/ExamineBaseTest.cs
Looking at stack traces reported from SyncedFileSystemDirectoryFactory shows that the errors always come from when the directory is first opened (i.e. site startup). 
This adds an index checker and the ability to try to repair the index. The check will happen before the index is attempted to be open. If the check fails, it will try to fix it and report on the outcome. If a fix occurs, this generally means that documents may be lost, however, they might have been removed documents in the first place but the segments file wasn't updated during the syncing.
The index will then attempted to be read, if that fails, a new index will be created.
> Fixing SyncedFileSystemDirectoryFactory when the main index is corrupted
